logging:
  level:
    org.springframework.security: INFO
    
spring:
  datasource:
    url: jdbc:mysql://hcl-capstone-ecommerce-group1.mysql.database.azure.com:3306/ecommerce
    username: good_buy_admin
    password: JulyJoiners!2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    show-sql: true
okta:
  oauth2:
    issuer: https://dev-06861319.okta.com/oauth2/default
    client-id: 0oa6b6zw9yWHxWJSo5d7
    client-secret: -fkooni-AVjHwfSbFwgvs1w9SXlFaHArXRirSdkj
    redirect-uri: /oauth2/callback/okta
         
server:
  port: 8081
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

app:
  cors:
    allowedOrigins: http://localhost:4200,http://localhost:8080,https://hcl-capstone-ecommerce-group1-frontend.azurewebsites.net
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
      - https://hcl-capstone-ecommerce-group1-frontend.azurewebsites.net/oauth2/redirect
      

stripe:
   key:
    secret: sk_test_51LfG2CDyv2YM2ORIjtiJkJGmGipL1DTVTfO9GKNq5uK4spVAuhRkLXCeRMg37JJZnb1bttWSajTgISZaKjQU8uGP00RHhtfS0s

  
