spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    show-sql: false
logging:
  level:
    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': DEBUG
okta:
  oauth2:
    issuer: https://dev-06861319.okta.com/oauth2/default
    client-id: 0oa6b6zw9yWHxWJSo5d7
    client-secret: -fkooni-AVjHwfSbFwgvs1w9SXlFaHArXRirSdkj
    redirect-uri: /oauth2/callback/okta
         
server:
  port: 8081
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
